
check-thread-count = 4
export-fix-sql = true
check-struct-only = false

######################### Datasource config #########################
[data-sources.mysql1]
    host = "10.0.3.7"
    port = 4000
    user = "root"
    password = "1234Abcd"

    route-rules = ["rule1"]

[data-sources.mysql2]
    host = "10.0.3.7"
    port = 4000
    user = "root"
    password = "1234Abcd"

    route-rules = ["rule2"]

[data-sources.tidb0]
    host = "10.0.3.7"
    port = 4000
    user = "root"
    password = "1234Abcd"

########################### Routes ###########################
[routes.rule1]
schema-pattern = "sourcedb01"
table-pattern = "source_table_01"
target-schema = "dmtarget"
target-table = "merged_table"

[routes.rule2]
schema-pattern = "sourcedb02"
table-pattern = "source_table_02"
target-schema = "dmtarget"
target-table = "merged_table"

######################### Task config #########################
[task]
    output-dir = "./output"
    source-instances = ["mysql1", "mysql2"]
    target-instance = "tidb0"
    target-check-tables = ["dmtarget.merged_table"]
